// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8htgBoX_WxEfRoi_WJXHyQ3H7q3nrf0',
    appId: '1:328780249799:web:68b047c42a04a14e281ce2',
    messagingSenderId: '328780249799',
    projectId: 'flutterz-3992d',
    authDomain: 'flutterz-3992d.firebaseapp.com',
    storageBucket: 'flutterz-3992d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-To3ynX-wIa8GAbHPcMW1nPYEcOWvnU',
    appId: '1:328780249799:android:bd79ef0c0c58cbe1281ce2',
    messagingSenderId: '328780249799',
    projectId: 'flutterz-3992d',
    storageBucket: 'flutterz-3992d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPZD8kQj_CDroYQcFcZncFYNjLz393As',
    appId: '1:328780249799:ios:53e52296edca6695281ce2',
    messagingSenderId: '328780249799',
    projectId: 'flutterz-3992d',
    storageBucket: 'flutterz-3992d.appspot.com',
    iosBundleId: 'com.example.z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPZD8kQj_CDroYQcFcZncFYNjLz393As',
    appId: '1:328780249799:ios:ff99a32d71ffb995281ce2',
    messagingSenderId: '328780249799',
    projectId: 'flutterz-3992d',
    storageBucket: 'flutterz-3992d.appspot.com',
    iosBundleId: 'com.example.z.RunnerTests',
  );
}
